version: "2"

checks:
  method-complexity:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50

plugins:
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
  eslint:
    enabled: true
    checks:
      global-require:
        enabled: false
  fixme:
    enabled: true

exclude_paths:
  - "LICENSE"
  - "README*"
  - "package.json"
  - "dist/"
  - "html/"
  - "test/"
