engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
  eslint:
    enabled: true
    checks:
      global-require:
        enabled: false
  fixme:
    enabled: true

ratings:
  paths:
    - "node/*"
    - "src/*.js"

exclude_paths:
  - "LICENCE"
  - "README*"
  - "package.json"
  - "build/"
  - "html/"
  - "tests/"
