language: node_js
node_js:
  - "lts/*"
addons:
  code_climate:
    repo_token: 463152bd2e69388dee05f432bb7ddebc863f6a22d197ebfe00b1ca0854f1cdcf
install:
  - npm install
script:
  - npm test
  - codeclimate-test-reporter < coverage/lcov.info
