env:
  global:
    - CC_TEST_REPORTER_ID=fde5ace99a6139558a65db012be99e51b6f09dc3bafde415187195ffd216d319
language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm test
  - codeclimate-test-reporter < coverage/lcov.info
