language: node_js
node_js:
  - "lts/*"
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --input-type lcov --exit-code $TRAVIS_TEST_RESULT
